### ISSUE TITLE
JSON file error

### ISSUE THREAD

**Issue by Bang1338** [kkrypt0nn/Python-Discord-Bot-Template#48]
============================Output============================
Traceback (most recent call last):
  File "C:\Users\Bang1338\Desktop\a\bot.py", line 26, in <module>
    config = json.load(file)
  File "C:\Users\Bang1338\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Bang1338\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Bang1338\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Bang1338\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 14 (char 131)
============================End============================
I don't know what is that but... 5 error at same time

**Comment by kkrypt0nn** [comment]
Hey - the content of the `config.json` file is not a valid JSON.
