### ISSUE TITLE
Improper token has been passed

### ISSUE THREAD

**Issue by snposa** [kkrypt0nn/Python-Discord-Bot-Template#55]
```
┌──(senpai㉿senpai)-[~/tools/Python-Discord-Bot-Template]
└─$ python bot.py
Loaded extension 'fun-slash'
Loaded extension 'owner-slash'
Loaded extension 'moderation-slash'
Loaded extension 'template-slash'
Loaded extension 'general-slash'
Loaded extension 'fun-normal'
Loaded extension 'moderation-normal'
Loaded extension 'general-normal'
Loaded extension 'template-normal'
Loaded extension 'owner-normal'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/disnake/http.py", line 467, in static_login
    data: user.User = await self.request(Route("GET", "/users/@me"))
  File "/usr/local/lib/python3.9/dist-packages/disnake/http.py", line 420, in request
    raise HTTPException(response, data)
disnake.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/senpai/tools/Python-Discord-Bot-Template/bot.py", line 216, in <module>
    bot.run(config["token"])
  File "/usr/local/lib/python3.9/dist-packages/disnake/client.py", line 856, in run
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/disnake/client.py", line 835, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/disnake/client.py", line 798, in start
    await self.login(token)
  File "/usr/local/lib/python3.9/dist-packages/disnake/client.py", line 658, in login
    data = await self.http.static_login(token.strip())
  File "/usr/local/lib/python3.9/dist-packages/disnake/http.py", line 471, in static_login
    raise LoginFailure("Improper token has been passed.") from exc
disnake.errors.LoginFailure: Improper token has been passed.
```

**Comment by notcooler** [comment]
ur token is wrong i think

**Comment by kkrypt0nn** [comment]
The error says all, the token you give is an invalid bot token.
