### ISSUE TITLE
Probleme Improper token has been passed

### ISSUE THREAD

**Issue by Matthieu-Solgaleo** [kkrypt0nn/Python-Discord-Bot-Template#83]
hello dear developer :)

Here I have a problem and this problem comes back on all the bots that I have and even with yours that I have just tested.

The bot tells me that my Token and "Improper token has been passed"

except it's the right one :) I even tried to reset it to put the new one and still the same message...

I specify that above all the bots on discord developer worked very well and for some time nothing has worked and I can't use any bot :(

do you know where the problem comes from? don't tell me it's from my Token before I had discord bots and it works great.

Thanks in advance, the error code and below:

PS C:\Users\tremp\Desktop\Python-Discord-Bot-Template-main> python bot.py
2023-03-15 20:08:55 INFO     discord_bot Loaded extension 'fun'
2023-03-15 20:08:55 INFO     discord_bot Loaded extension 'general'
2023-03-15 20:08:55 INFO     discord_bot Loaded extension 'moderation'
2023-03-15 20:08:55 INFO     discord_bot Loaded extension 'owner'
2023-03-15 20:08:55 INFO     discord_bot Loaded extension 'template'
2023-03-15 20:08:55 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.     
2023-03-15 20:08:55 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tremp\Desktop\Python-Discord-Bot-Template-main\bot.py", line 305, in <module>
    bot.run(config["token"])
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\client.py", line 777, in start
    await self.login(token)
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\client.py", line 612, in login
    data = await self.http.static_login(token)
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\http.py", line 805, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0330B778>
Traceback (most recent call last):
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\tremp\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by kkrypt0nn** [comment]
Hey hey,

Unfortunately that's nothing related to the template itself, hence the issue will be closed.

The error is clearly related to the bot's token being invalid and all I can recommend is reset the token once again and see if changes anything, otherwise try again in a few hours the same. Double check you've copied the token correctly as well, just to be sure.

Thanks a lot for the star 🌟

**Comment by Matthieu-Solgaleo** [comment]
I just reset it, still the same message and I try them on a simple bot in Node.js and it works! could it be something else?

**Comment by kkrypt0nn** [comment]
Not really, the issue is related to the token itself - you may have pasted the token incorrectly in the configuration file though.

**Comment by Matthieu-Solgaleo** [comment]
I do it by clicking on copy and try doing it manually and both ways with the bot in js and the one in python

**Comment by kkrypt0nn** [comment]
Can't really help you further, you can eventually show your configuration file and blur the token partially, or in its entirety.

**Comment by Matthieu-Solgaleo** [comment]
send it to you here?

**Comment by kkrypt0nn** [comment]
Sure, otherwise if you wish we can pursue on [Discord](https://go.krypton.ninja/discord).
